server:
  port: 9005

spring:
  application:
    name: index12306-aggregation${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.emv:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        import-check:
          enabled: false
      username: nacos
      password: nacos
    sentinel:
      transport:
        dashboard: localhost:8686
        port: 8719
  dynamic:
    thread-pool:
      nacos:
        data-id: hippo4j-nacos.yaml
        group: DEFAULT_GROUP
      config-file-type: yml
      executors:
        - thread-pool-id: 'select-seat-thread-pool-executor'
          alarm: false
          allow-core-thread-time-out: true
          blocking-queue: SynchronousQueue
          core-pool-size: 20
          maximum-pool-size: 40
          keep-alive-time: 9999
          rejected-handler: CallerRunsPolicy

  main:
    allow-bean-definition-overriding: true

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: index12306_aggregation-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

pay:
  alipay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiicnqfUP8HRKZkB3lRY78jVXF6jVyjN00iBc3lbngma6VvG6QS06QH0+EDp02lNb5/W4z9SXrmiSEBzL3xkUvId0LvcuxrnB63fAyHvjXjy/vhBBQBksyA5edvpPLEWyETUVnuqR24Vd32TnUr2YryxtNPVtods+IXswJ1SBH64GYr5dxy0OfXjmu5N4XMkZRUNjsGWbVrw0t1ZYSRpkEuQVpe4ZYRD/rKMBoIjAEcfsO6pFcddZtu6doy6lklkoxErOWt3HdpdUpOYO0AXmNBdN7X8kxKFryILFAc39V94ij1epKvEUvxiCsmgRhg27tJDykXgukSVgTVjO5UtQhwIDAQAB
    app-id: 9021000135601271
    charset: UTF8
    format: json
    notify-url: http://pydswv.natappfree.cc/api/pay-service/callback/alipay
    private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCc43nyQy0DadYw7wFMrpf4TkNbjrKoQzj6wq58JlyBSqmRIhbcMIDUtapTXrfxagt6nxWikel9QWuYNC+tAn8Zm/YmqtjjYmw3zsCmzBP5y+I3/IDyuINSu7tngsXnEuyd18fVCG6n2N6fZkJA6KxQRZ/f03tEGPcM0fENbkYmP1aUkv/7RwuQ7WGBtbh4QEXfazcJZxkZsFn84IZozeSfA3WBIkmLf+sUxmiPd23YGS5nWXQOZXkM3Rg8Yx+kzfBwo/hzUkKxnVXJ9CRQBNAkI2Xv1H3R15lcbQnmlwNHSHthb5Yr3P06Ehng3sMOm9U45Tf14hDFxoyOkvWOLw2JAgMBAAECggEAEJZYYU3K5458D+ZlG8dl1+Hmazq2FuYskw6cRhIEO8M6FFcnVZZnOJYQcQoVppeQqSFCt1J3/j85cfkqhT87UujTaJktnzTbvjbE1Z3ECugMfeDbfU4WzFt+393KsLimfbW/sf1XPbXHK9Ey9gvjlAUYdyCz6qo9DITx2HqtPgPPJiJEuTW06JNTTOfSptSZ/RVg//KL1QeHaiZyViHstM6nlvpHAxxO0pKaV1zjPfRXPMJAZDb0WWj5OhMck+1anoaqcbW3V7ASTWPWNja9b82JUoRQtV6MMeH3znd2vHf8nLRmEy9HjF5xyhIUb2kgfGJKQbU8bzNRQ6LY2bX6RQKBgQDzM9JDVSZep4FyRepG1XLoWKMtTJLvGX5/aqvxlsZ67WvjRR9jsRtXtXXCwaUFqG7DIrbsGWVp0cs34vsUHRN1GYTunfL8alKzF5MZRAxy8ri8JImuuLY6Ypgg5uImz+FJqwIhCLGNGOUeuSumPDNzKc3lcpm6dLhWbH8a/xxQ0wKBgQClJOvuqAhvM4bo6EE+oEfPxpLoB9ikh6m6SsGynVWF5L/KeuYLFJuzqu2ZIfoQl7i1yOvKLy17gal62zkGgQswYYePar1WaLZoamcd9hmN+pbrjmsXc052IBCga6c4dwHGIwMPjQHiKJCxZDjptQ09nHSWdPdYjeDJlkTmeM0OswKBgQC+P2SVPZAFbZ2KifzJqoH4FhaYAhXTKqtU+1pEY8EiOoYyRElY0BvmkdHsJ1VzRp5W0doseXVmwTHqpwnoYxJsgSkHDNIe+QF2jdOJaT0f0pYGv8JgxqfupmABJPv2hpni6f6BXu6dxMK/NPVbVi6dQS+K9Qoi3Nmy6a7IrJY29wKBgQCBa436WnVBsH/pxxpamgGtM1GtxXhieG7rL+rcr7B2Xe5wICBoTp43D51khNwUZNK8o9klehOK1vKa9XKbRkYehFBYdK4tKaLJ8ZkeQd+FBP2BXPtQRW0X5ckh7zv9ZEZfoNClPzxaoK/EVWbEwL6/qf00bDXrkES5tqoIdGM/QQKBgQDKo2cJy+0xRz2zAbE7fr0+2+eqfBJVFC5lUSSwtklKTTc5U9sKAwL5BMt/gzoO9Ul2JnWou5ojdL81CnpIESGF/h3kXjhUFslSHZ/wfBlX7X67Dtem85w999TKFkrAkaGqRFREMOz4SdlCq0h77vMbwO9XlBpvUzfOAe9AoxZOzQ==
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    sign-type: RSA2

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aggregation:
  remote-url: http://127.0.0.1:${server.port}

framework:
  fastjson:
    safa-mode: true
  cache:
    redis:
      value-timeout: 50000
      bloom-filter:
        user-register:
          name: user_register_cache_penetration_bloom_filter${unique-name:}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

ticket:
  availability:
    cache-update:
      type: binlog